export const BASE_URL='https://mashghol.com/savoz-backend/v1/'


export const endpoints={
     signinUrl:`admin/login`,
     forgotPasswordUrl:`admin/reset_password`,
     logoutUrl:`logout`,
     productListingUrl:`admin/products/get-all-products?page=`,
     subCategoryListingUrl:`admin/categories/get-categories`,
     validateResetPasswordUrl:`admin/validate_reset_token`,
     validateAuthResetPasswordUrl:`auth/validate_reset_token`,
     resetPasswordUrl:`admin/new_password`,
     resetAuthPasswordUrl:`auth/new_password`,
     getProductCategories:`admin/product-categories/get-product-categories`,
     adminProfilePictureUrl:`admin/upload_profile`,
     adminProfileUpdate:`admin/update_profile`,
     addCategory:`admin/categories/add-sub-category`,
     deleteCategory:`admin/categories/delete-category/`,
     updateCategory:`admin/categories/update-category`,
     getCategoryById:`admin/categories/get-category/`,
     productCategoryListingUrl:`admin/product-categories/get-product-categories`,
     productCategoryListingUrlAll:`admin/product-categories/get-product-categories-list`,
     addProductCategory:`admin/product-categories/add-product-category`,
     updateProductCategory:`admin/product-categories/update`,
     deleteProductCategory:`admin/product-categories/delete-category/`,
     addProduct:`admin/products/add-product`,
     updateProduct:`admin/products/update-product`,
     deleteProduct:`admin/products/delete-product`,
     getListOfUsers:`admin/employees/get-employees`,
     userImageUpload:`admin/employees/upload-profile-image`,
     addUser:`admin/employees/add`,
     updateUser:`admin/employees/update`,
     deleteUser:`admin/employees/delete-employee`,
     getUserInfo:`admin/employees/get-employee/`,
     getPaginatedUsers:`admin/employees/get-employees?page=`,
     allOrders:`admin/all_orders`,
     assignOrder:`admin/assign_rider`,
     productBulkImport:`admin/products/bulk-upload`,
     productCategoriesBulkImport:`admin/product-categories/bulk-upload`,
     categoriesBulkImport:`admin/categories/bulk-upload`,
     dashboardStatistics:`admin/dashboard/statistics`,
getBillingDetails:`order/order_receipt/`

}